# blue_deployment.yaml (Configuration for Rolling Update to V2)

# Part 1: Define the Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  labels:
    app: django-app
spec:
  # The desired replica count (3 from Task 2)
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-messaging-container
        image: hashicorp/http-echo:latest # <-- Guaranteed to exist!
        args: ["-listen=:5678", "-text=ALX Kubernetes App V2.0 ROLLING Update!"] 
        ports:

--- 

# Part 2: Define the Service (Required to be in file, though unchanged)
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  selector:
    app: django-app